import React from "react";
import "../styles/globals.css";

interface LayoutProps {
  children: React.ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>Anima Project - Automatically generated by Anima</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
          {`@import url("https://fonts.googleapis.com/css?family=Inter:var(--habibauiux-framer-website-semantic-heading-2-font-weight),var(--habibauiux-framer-website-inter-regular-font-weight),var(--habibauiux-framer-website-semantic-heading-1-font-weight),500,var(--habibauiux-framer-website-inter-bold-font-weight),400,var(--habibauiux-framer-website-semantic-link-font-weight),var(--habibauiux-framer-website-inter-medium-font-weight)|Figtree:500,600,var(--habibauiux-framer-website-figtree-medium-font-weight)|Instrument+Serif:400,italic|Chewy:400");`}
        </style>
      </head>
      <body>
        <div id="app">{children}</div>
      </body>
    </html>
  );
}